### WORKING WITH CADDY

version: '3.9'

networks:
   caddy:

volumes:
    geoserver-data:
    geo-db-data:
    caddy_data:
      external: true
    caddy_config:
    settings:

services:
   db:  # this is the host name also when connecting to geoserver
      image: kartoza/postgis:${POSTGIS_VERSION_TAG}
      volumes:
        - ./geo-db-data:/var/lib/postgresql
        - ./site_summary_grant_id_ha_4326.sql:/docker-entrypoint-initdb.d/site_summary_grant_id_ha_4326.sql
      ports:
        - ${POSTGRES_PORT}:5432
      environment:
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASS=${POSTGRES_PASS}
        - ALLOW_IP_RANGE=${ALLOW_IP_RANGE}
        - FORCE_SSL=TRUE
        - POSTGRES_MULTIPLE_EXTENSIONS=postgis,postgis_topology
      restart: on-failure
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      networks:
        - caddy

   geoserver:
      image: kartoza/geoserver:${GS_VERSION}
      build:
        context: .
        args:
          IMAGE_VERSION: ${IMAGE_VERSION}
          JAVA_HOME: ${JAVA_HOME}
          GS_VERSION: ${GS_VERSION}
          WAR_URL: ${WAR_URL}
          DOWNLOAD_ALL_STABLE_EXTENSIONS: ${DOWNLOAD_ALL_STABLE_EXTENSIONS}
          DOWNLOAD_ALL_COMMUNITY_EXTENSIONS: ${DOWNLOAD_ALL_COMMUNITY_EXTENSIONS}
          STABLE_PLUGIN_BASE_URL: ${STABLE_PLUGIN_BASE_URL}
      volumes:
        - geoserver-data:/opt/geoserver/data_dir
        - settings:/settings
      ports:
        - ${GEOSERVER_PORT}:8080
      restart: on-failure
      environment:
        - GEOSERVER_DATA_DIR=${GEOSERVER_DATA_DIR}
        - GEOWEBCACHE_CACHE_DIR=${GEOWEBCACHE_CACHE_DIR}
        - GEOSERVER_ADMIN_PASSWORD=${GEOSERVER_ADMIN_PASSWORD}
        - GEOSERVER_ADMIN_USER=${GEOSERVER_ADMIN_USER}
        - INITIAL_MEMORY=${INITIAL_MEMORY}
        - MAXIMUM_MEMORY=${MAXIMUM_MEMORY}
        - RECREATE_DATADIR=${RECREATE_DATADIR}
        - STABLE_EXTENSIONS=${STABLE_EXTENSIONS}
        - COMMUNITY_EXTENSIONS=${COMMUNITY_EXTENSIONS}
        # this is needed to allow for form submissions that don't originate from geoserver such as through a proxyserver 
        - GEOSERVER_CSRF_WHITELIST=${URL_NAME}
      healthcheck:
        test: "curl --fail --silent --write-out 'HTTP CODE : %{http_code}\n' --output /dev/null -u ${GEOSERVER_ADMIN_USER}:'${GEOSERVER_ADMIN_PASSWORD}' http://localhost:8080/geoserver/rest/about/version.xml"
        interval: 1m
        timeout: 10s
        retries: 3
      networks:
        - caddy
   caddy:
      image: caddy:latest
      restart: unless-stopped
      container_name: caddy
      ports:
        - 80:80
        - 443:443
      volumes:
        - /home/ubuntu/pa-geoserver-test/kartoza_postgis_geoserver/caddy/Caddyfile:/etc/caddy/Caddyfile
        - /home/ubuntu/pa-geoserver-test/kartoza_postgis_geoserver/caddy/site:/srv
        - /home/ubuntu/pa-geoserver-test/kartoza_postgis_geoserver/caddy/caddy_data:/data
        - /home/ubuntu/pa-geoserver-test/kartoza_postgis_geoserver/caddy/caddy_config:/config
      networks:
        - caddy