version: "3.9"  # optional since v1.27.0

services:
  db:
    # postgis image name
    image: kartoza/postgis:14-3.1
    volumes:
      # in a docker context, volumes are mountable file systems to preserve data and can persist beyond the life cycle of the container
      # for more info see here https://docs.docker.com/storage/volumes/
      # standard volume for data persistence
      - postgis-data:/var/lib/postgresql
      # test data to be loaded on startup of container
      # this can be replaced or added to with another sql dump, just enter a new line and copy the syntax below and replace test_data.sql
      - ./site_level_information_grouped.sql:/docker-entrypoint-initdb.d/site_level_information_grouped.sql
    environment:
      # generic postgres environment variables from .env file
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASS=${POSTGRES_PASS}
      - ALLOW_IP_RANGE=0.0.0.0/0
      # DB extensions to enable within the database
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,postgis_topology
    ports:
      # Maps container port 5432 to localhost port 5432
      - 5432:5432
    # if container failures this will cause an auto restart
    restart: on-failure
    healthcheck:
      # healthcheck to prevent web container failing at startup
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5


volumes:
  postgis-data: